# Generated by Django 3.0.5 on 2024-02-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0009_auto_20240228_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feature',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
