# Generated by Django 3.0.5 on 2024-02-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_auto_20240228_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='feature',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
